es-base-objects/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <label>Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Space__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Block Room</fullName>
            </value>
            <value>
                <fullName>Café</fullName>
            </value>
            <value>
                <fullName>Cooking Classroom</fullName>
            </value>
            <value>
                <fullName>Drawing/Watercolor Studio</fullName>
            </value>
            <value>
                <fullName>Exploration Lab</fullName>
            </value>
            <value>
                <fullName>Game Room/Arcade</fullName>
            </value>
            <value>
                <fullName>Music Room</fullName>
            </value>
            <value>
                <fullName>Sand Drawing Tables</fullName>
            </value>
            <value>
                <fullName>Temporary Terrace</fullName>
            </value>
            <value>
                <fullName>Walking Meditation Paths</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Daily_Booking_Rate__c.field-meta.xml
<CustomField>
    <fullName>Daily_Booking_Rate__c</fullName>
    <label>Base Daily Booking Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <label>Maximum Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Minimum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Capacity__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Minimum Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Types</valueSetName>
    </valueSet>
</CustomField>

es-base-objects/main/default/globalValueSets/Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Large Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled Activity</fullName>
    </customValue>
    <customValue>
        <fullName>Come-and-Go</fullName>
    </customValue>
    <customValue>
        <fullName>Individuals or Small Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Conversation Starter</fullName>
    </customValue>
    <customValue>
        <fullName>Quiet</fullName>
    </customValue>
    <customValue>
        <fullName>Energizing</fullName>
    </customValue>
    <customValue>
        <fullName>Relaxing</fullName>
    </customValue>
    <masterLabel>Types</masterLabel>
</GlobalValueSet>

es-base-code/main/default/classes/MarketServices.cls
public inherited sharing class MarketServices {
    @auraEnabled(cacheable=true)
    public static List<Space__c> getRelatedSpaces(Id recordId) {
        return [
            SELECT
                Id,
                Daily_Booking_Rate__c,
                Name,
                Market__c,
                Maximum_Capacity__c,
                Minimum_Capacity__c,
                Picture_URL__c,
                Category__c,
                Type__c
            FROM Space__c
            WHERE Market__c = :recordId
            WITH SECURITY_ENFORCED
        ];
    }
}