es-base-objects/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    
    <label>Reservation</label>
    <nameField>
        <displayFormat>{DD}{MM}{YY}-{0}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reservation_Status</valueSetName>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <label>Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Space__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

es-base-objects/main/default/globalValueSets/Reservation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Proposal Ready</fullName>
    </customValue>
    <customValue>
        <fullName>Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Reservation Status</masterLabel>
</GlobalValueSet>

es-space-mgmt/main/default/classes/reservationManagerControllerTest.cls
@isTest
public class reservationManagerControllerTest {
    
    @testSetup
    static void setup(){
        List<Account> accts = testDataFactory.makeAccounts(15);
        List<Contact> contacts = testDataFactory.makeContacts(25);
        List<Lead> leads = testDataFactory.makeLeads(25);
        List<Market__c> markets = testDataFactory.makeMarkets(25);
        List<Space__c> allSpaces = new List<Space__c>();
        List<Reservation__c> reservs = testDataFactory.makeReservations(12);

        insert leads;
        insert accts;
        Integer counter = 0;
        for(Contact c: contacts){
            c.AccountId = accts[counter].Id;
            counter++;
            if(counter >= accts.size()) counter = 0; 
        }
        insert contacts;

        insert markets;
        for(Integer i=0;i <markets.size();i++){
            List<Space__c> spaces = testDataFactory.makeSpaces(12);
            for(Space__c s: spaces){
                s.Market__c = markets[i].Id;
            }
            allSpaces.addAll(spaces);
        }
        insert allSpaces;

        counter = 0;
        for(Reservation__c r: reservs){
            r.Market__c = markets[0].Id;
            if(Math.mod(counter, 2)==0){
                r.Contact__c = contacts[counter].Id;
                r.Status__c = 'Draft';
            }else{
                r.Lead__c = leads[counter].Id;
                r.Status__c = 'Not Started';
            }
            counter++;
        }
        insert reservs;

    }

    @isTest
    static void canFetchCustomers(){
        List<customerServices.Customer> contacts = reservationManagerController.getCustomerList('Contact');
        system.assertNotEquals(contacts, NULL);
        List<customerServices.Customer> leads = reservationManagerController.getCustomerList('Lead');
        system.assertNotEquals(leads, NULL);
        system.assertNotEquals(contacts, leads);
    }

    @isTest 
    static void canFetchOpenReservs(){
        List<Reservation__c> reservs = reservationManagerController.getOpenReservations();
        system.assertNotEquals(reservs, NULL);
        system.assertEquals(reservs.size(), 10);
    }

}