es-base-objects/main/default/objects/Contact/fields/Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Status__c</fullName>
    <label>Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Proposal Ready</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    
    <label>Reservation</label>
    <nameField>
        <displayFormat>{DD}{MM}{YY}-{0}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reservation_Status</valueSetName>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Total_Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Guests__c</fullName>
    <label>Total Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

es-base-objects/main/default/globalValueSets/Reservation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Proposal Ready</fullName>
    </customValue>
    <customValue>
        <fullName>Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Reservation Status</masterLabel>
</GlobalValueSet>

es-space-mgmt/main/default/classes/reservationManagerController.cls
public with sharing class reservationManagerController {
    //Note: This is a sample, so we're using 'LIMIT' to simulate proper set/pagination controls
    @auraEnabled(cacheable=true)
    public static List<customerServices.Customer> getCustomerList(
        String sObjectType
    ) {
        List<customerServices.Customer> customers = new List<customerServices.Customer>();
        if (sObjectType == 'Lead') {
            for (Lead l : [
                SELECT Id, Email, Name, City, State, Status
                FROM Lead
                WHERE
                    Status IN (
                        'Open - Not Contacted',
                        'New - Not Contacted',
                        'New'
                    )
                WITH SECURITY_ENFORCED
                LIMIT 5
            ]) {
                customerServices.Customer c = new customerServices.Customer(
                    l.Name,
                    l.Email,
                    l.City,
                    l.State,
                    l.Status,
                    l.Id
                );
                customers.add(c);
            }
        }
        if (sObjectType == 'Contact') {
            for (Contact c : [
                SELECT
                    Id,
                    Email,
                    Name,
                    MailingCity,
                    MailingState,
                    Reservation_Status__c
                FROM Contact
                WHERE Reservation_Status__c IN ('Not Started')
                WITH SECURITY_ENFORCED
                LIMIT 5
            ]) {
                customerServices.Customer cu = new customerServices.Customer(
                    c.Name,
                    c.Email,
                    c.MailingCity,
                    c.MailingState,
                    c.Reservation_Status__c,
                    c.Id
                );
                customers.add(cu);
            }
        }
        return customers;
    }

    @auraEnabled(cacheable=true)
    public static List<Reservation__c> getOpenReservations() {
        return [
            SELECT
                Id,
                Name,
                Contact__c,
                Contact__r.Name,
                Lead__c,
                Lead__r.Name,
                Market__c,
                Market__r.Name,
                Status__c,
                Start_Date__c,
                End_Date__c,
                Total_Number_of_Guests__c
            FROM Reservation__c
            WHERE Status__c IN ('Not Started', 'Draft')
            WITH SECURITY_ENFORCED
            LIMIT 10
        ];
    }
}