es-base-objects/main/default/objects/Contact/fields/Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Status__c</fullName>
    <label>Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Proposal Ready</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>>
    </valueSet>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/Customer_Fields__mdt.object-meta.xml
<CustomObject>
    <description>Used to determine appropriate fields for customer contact forms. Used to allow Lightning components to use Lead and Contact objects interchangeably.</description>
    <label>Customer Fields</label>
    <pluralLabel>Customer Fields</pluralLabel>
</CustomObject>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Reservation_Status_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reservation_Status_Value__c</fullName>
    <label>Customer Reservation Status Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Sobject_Type__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type__c</fullName>
    <label>Sobject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

es-space-mgmt/main/default/classes/ReservationManagerTest.cls
@isTest
private class ReservationManagerTest {
    @testSetup
    static void setup() {
        List<Account> accts = TestDataFactory.makeAccounts(15);
        List<Contact> contacts = TestDataFactory.makeContacts(25);
        List<Lead> leads = TestDataFactory.makeLeads(25);

        insert leads;
        insert accts;
        Integer counter = 0;
        for (Contact c : contacts) {
            c.AccountId = accts[counter].Id;
            counter++;
            if (counter >= accts.size())
                counter = 0;
        }
        insert contacts;
    }

    @isTest
    static void canUpdateLeadReservationStatus() {
        Lead lead = [SELECT Id FROM Lead LIMIT 1];
        ReservationManager.Requests request = new ReservationManager.Requests();
        request.recordId = lead.Id;
        List<Id> lstIds = ReservationManager.updateReservationStatus(
            new List<ReservationManager.Requests>{ request }
        );
        List<Customer_Fields__mdt> lstcmdts = [
            SELECT
                Customer_Status__r.QualifiedAPIName,
                Customer_Reservation_Status_Value__c
            FROM Customer_Fields__mdt
            WHERE Sobject_Type__r.QualifiedAPIName = 'Lead'
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        Lead updatedLeadRecord = [
            SELECT Id, Status
            FROM Lead
            WHERE Id = :lstIds[0]
            LIMIT 1
        ];
        System.assertEquals(
            lstcmdts[0].Customer_Reservation_Status_Value__c,
            updatedLeadRecord.Status
        );
    }

    @isTest
    static void canUpdateContactReservationStatus() {
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        ReservationManager.Requests request = new ReservationManager.Requests();
        request.recordId = contact.Id;
        List<Id> lstIds = ReservationManager.updateReservationStatus(
            new List<ReservationManager.Requests>{ request }
        );
        List<Customer_Fields__mdt> lstcmdts = [
            SELECT
                Customer_Status__r.QualifiedAPIName,
                Customer_Reservation_Status_Value__c
            FROM Customer_Fields__mdt
            WHERE Sobject_Type__r.QualifiedAPIName = 'Contact'
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        Contact updatedContactRecord = [
            SELECT Id, Reservation_Status__c
            FROM Contact
            WHERE Id = :lstIds[0]
            LIMIT 1
        ];
        System.assertEquals(
            lstcmdts[0].Customer_Reservation_Status_Value__c,
            updatedContactRecord.Reservation_Status__c
        );
    }
}