es-base-objects/main/default/objects/Contact/fields/Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Status__c</fullName>
    <label>Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Proposal Ready</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Market__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

es-base-objects/main/default/objects/Market__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Trinidad and Tobago</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>South Africa</fullName>
            </value>
            <value>
                <fullName>Amsterdam</fullName>
            </value>
        </valueSetDefinition>>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Market__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    
    <label>Reservation</label>
    <nameField>
        <displayFormat>{DD}{MM}{YY}-{0}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Total_Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Guests__c</fullName>
    <label>Total Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <label>Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Space__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Building Block Room</fullName>
            </value>
            <value>
                <fullName>Café</fullName>
            </value>
            <value>
                <fullName>Cooking Classroom</fullName>
            </value>
            <value>
                <fullName>Drawing/Watercolor Studio</fullName>
            </value>
            <value>
                <fullName>Exploration Lab</fullName>
            </value>
            <value>
                <fullName>Game Room/Arcade</fullName>
            </value>
            <value>
                <fullName>Music Room</fullName>
            </value>
            <value>
                <fullName>Sand Drawing Tables</fullName>
            </value>
            <value>
                <fullName>Temporary Terrace</fullName>
            </value>
            <value>
                <fullName>Walking Meditation Paths</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Daily_Booking_Rate__c.field-meta.xml
<CustomField>
    <fullName>Daily_Booking_Rate__c</fullName>
    <label>Base Daily Booking Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <label>Maximum Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Minimum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Capacity__c</fullName>
    <defaultValue>2</defaultValue>
    <label>Minimum Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

es-base-objects/main/default/objects/Space__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Types</valueSetName>
    </valueSet>
</CustomField>

es-base-objects/main/default/globalValueSets/Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Large Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled Activity</fullName>
    </customValue>
    <customValue>
        <fullName>Come-and-Go</fullName>
    </customValue>
    <customValue>
        <fullName>Individuals or Small Groups</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor</fullName>
    </customValue>
    <customValue>
        <fullName>Conversation Starter</fullName>
    </customValue>
    <customValue>
        <fullName>Quiet</fullName>
    </customValue>
    <customValue>
        <fullName>Energizing</fullName>
    </customValue>
    <customValue>
        <fullName>Relaxing</fullName>
    </customValue>
    <masterLabel>Types</masterLabel>
</GlobalValueSet>

es-base-code/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Account> makeAccounts(Integer acctNum) {
        //make some Accounts
        List<Account> testAccts = new List<Account>();
        for (Integer x = 0; x < acctNum; x++) {
            Account a = new Account();
            a.Name = 'Test Account' + x;
            testAccts.add(a);
        }
        return testAccts;
    }

    public static List<Contact> makeContacts(Integer contactNum) {
        List<Contact> testPeeps = new List<Contact>();
        for (Integer x = 0; x < contactNum; x++) {
            Contact c = new Contact();
            c.FirstName = 'Testing' + x;
            c.LastName = 'Contact' + x;
            c.MailingCity = 'Test City' + x;
            c.MailingStreet = 'Test City Ave' + x;
            c.MailingState = Math.mod(x, 2) == 0
                ? null
                : (Math.mod(x, 3) == 0 ? 'NY' : 'OR');
            c.MailingPostalCode = Math.mod(x, 2) == 0
                ? '1011 AJ'
                : (Math.mod(x, 3) == 0 ? '10006' : '97230');
            c.MailingCountry = Math.mod(x, 2) == 0
                ? 'Amsterdam'
                : 'United States';
            c.Reservation_Status__c = 'Not Started';
            testPeeps.add(c);
        }
        return testPeeps;
    }

    public static List<Lead> makeLeads(Integer leadNum) {
        List<Lead> testPeeps = new List<Lead>();
        for (Integer x = 0; x < leadNum; x++) {
            Lead l = new Lead();
            l.FirstName = 'Test' + x;
            l.LastName = 'Lead' + x;
            l.Company = 'Test Company' + x;
            l.City = 'Test City' + x;
            l.Street = 'Test Street' + x;
            l.State = Math.mod(x, 2) == 0
                ? null
                : (Math.mod(x, 3) == 0 ? 'NY' : 'OR');
            l.Country = Math.mod(x, 2) == 0 ? 'Amsterdam' : 'United States';
            l.PostalCode = Math.mod(x, 2) == 0
                ? '1011 AZ'
                : (Math.mod(x, 3) == 0 ? '10006' : '97230');
            testPeeps.add(l);
        }
        return testPeeps;
    }

    public static List<Market__c> makeMarkets(Integer marketsNum) {
        List<Market__c> markets = new List<Market__c>();
        for (Integer x = 0; x < marketsNum; x++) {
            Market__c m = new Market__c();
            m.Name = 'Test Market' + x;
            m.City__c = 'Test City' + x;
            m.State__c = Math.mod(x, 2) == 0
                ? null
                : (Math.mod(x, 3) == 0 ? 'NY' : 'OR');
            m.Country__c = Math.mod(x, 2) == 0 ? 'Amsterdam' : 'United States';
            markets.add(m);
        }
        return markets;
    }

    public static List<Space__c> makeSpaces(Integer spacesNum) {
        List<Space__c> spaces = new List<Space__c>();
        for (Integer x = 0; x < spacesNum; x++) {
            Space__c s = new Space__c();
            s.Name = 'Test Space - ' + x;
            s.Daily_Booking_Rate__c = Decimal.valueOf((x + 10) * 1000);
            s.Category__c = Math.mod(x, 2) == 0
                ? 'Cooking Classroom'
                : (Math.mod(x, 3) == 0 ? 'Café' : 'Exploration Lab');
            s.Maximum_Capacity__c = (x + 1) * 10;
            s.Minimum_Capacity__c = x + 1;
            s.Picture_URL__c = 'https://pics.net.com/' + x;
            s.Type__c = Math.mod(x, 2) == 0
                ? 'Conversation Starter;Large Groups;Outdoor;Energizing;Scheduled Activity'
                : (Math.mod(x, 3) == 0
                      ? 'Individuals or Small Groups;Come-and-Go;Indoor;Relaxing;Quiet'
                      : 'Scheduled Activity;Come-and-Go;Indoor;Outdoor;Large Groups;Relaxing;Conversation Starter');
            spaces.add(s);
        }
        return spaces;
    }

    public static List<Reservation__c> makeReservations(Integer resvNumber) {
        List<Reservation__c> resrvs = new List<Reservation__c>();
        for (Integer x = 0; x < resvNumber; x++) {
            Reservation__c r = new Reservation__c();
            r.Start_Date__c = Date.today();
            r.End_Date__c = Date.today().addDays(x);
            r.Total_Number_of_Guests__c = x + 10;
            resrvs.add(r);
        }
        return resrvs;
    }
}