es-base-objects/main/default/objects/Contact/fields/Reservation_Status__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Status__c</fullName>
    <label>Reservation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Proposal Ready</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>>
    </valueSet>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/Customer_Fields__mdt.object-meta.xml
<CustomObject>
    <description>Used to determine appropriate fields for customer contact forms. Used to allow Lightning components to use Lead and Contact objects interchangeably.</description>
    <label>Customer Fields</label>
    <pluralLabel>Customer Fields</pluralLabel>
</CustomObject>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Reservation_Status_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reservation_Status_Value__c</fullName>
    <label>Customer Reservation Status Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Sobject_Type__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type__c</fullName>
    <label>Sobject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

es-base-objects/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    
    <label>Reservation</label>
    <nameField>
        <displayFormat>{DD}{MM}{YY}-{0}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reservation_Status</valueSetName>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <label>Space</label>
    <nameField>
        <label>Space Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Space__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Spaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

es-base-objects/main/default/globalValueSets/Reservation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Proposal Ready</fullName>
    </customValue>
    <customValue>
        <fullName>Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Reservation Status</masterLabel>
</GlobalValueSet>

es-space-mgmt/main/default/classes/ReservationManagerControllerTest.cls
@isTest
public class ReservationManagerControllerTest {
    @testSetup
    static void setup() {
        List<Account> accts = TestDataFactory.makeAccounts(15);
        List<Contact> contacts = TestDataFactory.makeContacts(25);
        List<Lead> leads = TestDataFactory.makeLeads(25);
        List<Market__c> markets = TestDataFactory.makeMarkets(25);
        List<Space__c> allSpaces = new List<Space__c>();
        List<Reservation__c> reservs = TestDataFactory.makeReservations(12);

        insert leads;
        insert accts;
        Integer counter = 0;
        for (Contact c : contacts) {
            c.AccountId = accts[counter].Id;
            counter++;
            if (counter >= accts.size())
                counter = 0;
        }
        insert contacts;

        insert markets;
        for (Integer i = 0; i < markets.size(); i++) {
            List<Space__c> spaces = TestDataFactory.makeSpaces(12);
            for (Space__c s : spaces) {
                s.Market__c = markets[i].Id;
            }
            allSpaces.addAll(spaces);
        }
        insert allSpaces;

        counter = 0;
        for (Reservation__c r : reservs) {
            r.Market__c = markets[0].Id;
            if (Math.mod(counter, 2) == 0) {
                r.Contact__c = contacts[counter].Id;
                r.Status__c = 'Draft';
            } else {
                r.Lead__c = leads[counter].Id;
                r.Status__c = 'Not Started';
            }
            counter++;
        }
        insert reservs;
    }

    @isTest
    static void canFetchCustomers() {
        List<CustomerServices.Customer> contacts = ReservationManagerController.getCustomerList(
            'Contact'
        );
        system.assertNotEquals(contacts, null);
        List<CustomerServices.Customer> leads = ReservationManagerController.getCustomerList(
            'Lead'
        );
        system.assertNotEquals(leads, null);
        system.assertNotEquals(contacts, leads);
    }

    @isTest
    static void canFetchOpenReservs() {
        List<Reservation__c> reservs = ReservationManagerController.getOpenReservations();
        system.assertNotEquals(reservs, null);
        system.assertEquals(reservs.size(), 10);
    }

    @isTest
    static void canupdateLeadReservationStatus() {
        Lead lead = [SELECT Id FROM Lead LIMIT 1];
        ReservationManagerController.Requests request = new ReservationManagerController.Requests();
        request.recordId = lead.Id;
        List<Id> lstIds = ReservationManagerController.updateReservationStatus(
            new List<ReservationManagerController.Requests>{ request }
        );
        List<Customer_Fields__mdt> lstcmdts = [
            SELECT
                Customer_Status__r.QualifiedAPIName,
                Customer_Reservation_Status_Value__c
            FROM Customer_Fields__mdt
            WHERE Sobject_Type__r.QualifiedAPIName = 'Lead'
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        Lead updatedLeadRecord = [
            SELECT Id, Status
            FROM Lead
            WHERE Id = :lstIds[0]
            LIMIT 1
        ];
        System.assertEquals(
            lstcmdts[0].Customer_Reservation_Status_Value__c,
            updatedLeadRecord.Status
        );
    }

    @isTest
    static void canupdateContactReservationStatus() {
        Contact contact = [SELECT Id FROM Contact LIMIT 1];
        ReservationManagerController.Requests request = new ReservationManagerController.Requests();
        request.recordId = contact.Id;
        List<Id> lstIds = ReservationManagerController.updateReservationStatus(
            new List<ReservationManagerController.Requests>{ request }
        );
        List<Customer_Fields__mdt> lstcmdts = [
            SELECT
                Customer_Status__r.QualifiedAPIName,
                Customer_Reservation_Status_Value__c
            FROM Customer_Fields__mdt
            WHERE Sobject_Type__r.QualifiedAPIName = 'Contact'
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        Contact updatedContactRecord = [
            SELECT Id, Reservation_Status__c
            FROM Contact
            WHERE Id = :lstIds[0]
            LIMIT 1
        ];
        System.assertEquals(
            lstcmdts[0].Customer_Reservation_Status_Value__c,
            updatedContactRecord.Reservation_Status__c
        );
    }
}