es-base-code/main/default/objects/Customer_Fields__mdt/Customer_Fields__mdt.object-meta.xml
<CustomObject>
    <description>Used to determine appropriate fields for customer contact forms. Used to allow Lightning components to use Lead and Contact objects interchangeably.</description>
    <label>Customer Fields</label>
    <pluralLabel>Customer Fields</pluralLabel>
</CustomObject>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Reservation_Status_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reservation_Status_Value__c</fullName>
    <label>Customer Reservation Status Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Sobject_Type__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type__c</fullName>
    <label>Sobject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

es-space-mgmt/main/default/classes/ReservationManager.cls
public with sharing class ReservationManager {
    @InvocableMethod(label='Update Reservation Status')
    public static List<Id> updateReservationStatus(
        List<Requests> recordsToUpdate
    ) {
        Schema.SObjectType sObjectType;
        SObject recordToUpdate;
        String objectName;
        List<Id> sucessIds = new List<Id>();
        if (recordsToUpdate.size() > 0) {
            // Safe navigate to avoid null pointers
            sObjectType = recordsToUpdate[0].recordId?.getSObjectType();
            objectName = sObjectType?.getDescribe()?.getName();
            // Query custom Metadata Records to update sObject type
            List<Customer_Fields__mdt> lstcmdts = [
                SELECT
                    Customer_Status__r.QualifiedAPIName,
                    Customer_Reservation_Status_Value__c
                FROM Customer_Fields__mdt
                WHERE Sobject_Type__r.QualifiedAPIName = :objectName
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            if (lstcmdts.size() == 1) {
                Customer_Fields__mdt cmdt = lstcmdts[0];
                recordToUpdate = sObjectType.newSObject(
                    recordsToUpdate[0].recordId
                );
                recordToUpdate.put(
                    cmdt.Customer_Status__r.QualifiedAPIName,
                    cmdt.Customer_Reservation_Status_Value__c
                );
                // Check for CRUD and FLS
                SObjectAccessDecision decision = Security.stripInaccessible(
                    AccessType.UPDATABLE,
                    new List<SObject>{ recordToUpdate },
                    true
                );
                List<SObject> lstToUpdate = decision.getRecords();
                try {
                    update lstToUpdate;
                    sucessIds.add(lstToUpdate[0].Id);
                } catch (exception e) {
                    throw new ReservationManagerException(e.getMessage());
                }
            }
        }
        return sucessIds;
    }

    public class Requests {
        @InvocableVariable
        public Id recordId;
    }

    public class ReservationManagerException extends Exception {
    }
}