es-base-code/main/default/objects/Customer_Fields__mdt/Customer_Fields__mdt.object-meta.xml
<CustomObject>
    <description>Used to determine appropriate fields for customer contact forms. Used to allow Lightning components to use Lead and Contact objects interchangeably.</description>
    <label>Customer Fields</label>
    <pluralLabel>Customer Fields</pluralLabel>
</CustomObject>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_City__c.field-meta.xml
<CustomField>
    <fullName>Customer_City__c</fullName>
    <inlineHelpText
    >Enter the API name of the field that holds the customer&apos;s city information.</inlineHelpText>
    <label>Customer City</label>
    <metadataRelationshipControllingField
    >Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Draft_Status_Values__c.field-meta.xml
<CustomField>
    <fullName>Customer_Draft_Status_Values__c</fullName>
    <label>Customer Draft Status Values</label>
    <type>TextArea</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields_Email</relationshipLabel>
    <relationshipName>Customer_Fields_Email</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields_Name</relationshipLabel>
    <relationshipName>Customer_Fields_Name</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Reservation_Status_Value__c.field-meta.xml
<CustomField>
    <fullName>Customer_Reservation_Status_Value__c</fullName>
    <label>Customer Reservation Status Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_State__c.field-meta.xml
<CustomField>
    <fullName>Customer_State__c</fullName>
    <inlineHelpText>Enter the API name of the field that holds the customer&apos;s state information.</inlineHelpText>
    <label>Customer State</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Customer_Fields1</relationshipLabel>
    <relationshipName>Customer_Fields1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Sobject_Type__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type__c</fullName>
    <label>Sobject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

es-base-objects/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    
    <label>Reservation</label>
    <nameField>
        <displayFormat>{DD}{MM}{YY}-{0}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

es-base-objects/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Reservation_Status</valueSetName>
    </valueSet>
</CustomField>

es-base-objects/main/default/objects/Reservation__c/fields/Total_Number_of_Guests__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Guests__c</fullName>
    <label>Total Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

es-base-objects/main/default/globalValueSets/Reservation_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>Proposal Ready</fullName>
    </customValue>
    <customValue>
        <fullName>Contracted</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Reservation Status</masterLabel>
</GlobalValueSet>

es-space-mgmt/main/default/classes/ReservationManagerController.cls
public with sharing class ReservationManagerController {
    //Note: This is a sample, so we're using 'LIMIT' to simulate proper set/pagination controls
    @auraEnabled(cacheable=true)
    public static List<CustomerServices.Customer> getCustomerList(
        String sObjectType
    ) {
        List<CustomerServices.Customer> customers = new List<CustomerServices.Customer>();
        Customer_Fields__mdt c = [
            SELECT
                Customer_Name__r.QualifiedAPIName,
                Customer_Email__r.QualifiedAPIName,
                Customer_City__r.QualifiedAPIName,
                Customer_State__r.QualifiedAPIName,
                Customer_Status__r.QualifiedAPIName,
                Customer_Draft_Status_Values__c
            FROM Customer_Fields__mdt
            WHERE Sobject_Type__r.QualifiedAPIName = :sObjectType
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];

        List<String> draftStatus = new List<String>();
        draftStatus = c.Customer_Draft_Status_Values__c.split(',');

        String query = 'SELECT ';
        query += c.Customer_Name__r.QualifiedAPIName + ', ';
        query += c.Customer_Email__r.QualifiedAPIName + ', ';
        query += c.Customer_City__r.QualifiedAPIName + ', ';
        query += c.Customer_State__r.QualifiedAPIName + ', ';
        query += c.Customer_Status__r.QualifiedAPIName + ', ';
        query += 'Id';
        query += ' FROM ' + sObjectType;
        if (draftStatus.size() > 0) {
            query +=
                ' WHERE ' +
                c.Customer_Status__r.QualifiedAPIName +
                ' IN: draftStatus';
        }
        query += ' WITH SECURITY_ENFORCED LIMIT 5';

        for (Sobject sobj : Database.query(query)) {
            CustomerServices.Customer customer = new CustomerServices.Customer(
                (String) sobj.get(c.Customer_Name__r.QualifiedAPIName),
                (String) sobj.get(c.Customer_Email__r.QualifiedAPIName),
                (String) sobj.get(c.Customer_City__r.QualifiedAPIName),
                (String) sobj.get(c.Customer_State__r.QualifiedAPIName),
                (String) sobj.get(c.Customer_Status__r.QualifiedAPIName),
                (String) sobj.get('Id')
            );
            customers.add(customer);
        }
        return customers;
    }

    @auraEnabled(cacheable=true)
    public static List<Reservation__c> getOpenReservations() {
        return [
            SELECT
                Id,
                Name,
                Contact__c,
                Contact__r.Name,
                Lead__c,
                Lead__r.Name,
                Market__c,
                Market__r.Name,
                Status__c,
                Start_Date__c,
                End_Date__c,
                Total_Number_of_Guests__c
            FROM Reservation__c
            WHERE Status__c IN ('Not Started', 'Draft')
            WITH SECURITY_ENFORCED
            LIMIT 10
        ];
    }

    @InvocableMethod(label='Update Reservation Status')
    public static List<Id> updateReservationStatus(
        List<Requests> recordsToUpdate
    ) {
        Schema.SObjectType sObjectType;
        SObject recordToUpdate;
        String objectName;
        List<Id> sucessIds = new List<Id>();
        if (recordsToUpdate.size() > 0) {
            // Safe navigate to avoid null pointers
            sObjectType = recordsToUpdate[0].recordId.getSObjectType();
            objectName = sObjectType.getDescribe().getName();
            // Query custom Metadata Records to update sObject type
            List<Customer_Fields__mdt> lstcmdts = [
                SELECT
                    Customer_Status__r.QualifiedAPIName,
                    Customer_Reservation_Status_Value__c
                FROM Customer_Fields__mdt
                WHERE Sobject_Type__r.QualifiedAPIName = :objectName
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            if (lstcmdts.size() == 1) {
                Customer_Fields__mdt cmdt = lstcmdts[0];
                recordToUpdate = sObjectType.newSObject(
                    recordsToUpdate[0].recordId
                );
                recordToUpdate.put(
                    cmdt.Customer_Status__r.QualifiedAPIName,
                    cmdt.Customer_Reservation_Status_Value__c
                );
                // Check for CRUD and FLS
                SObjectAccessDecision decision = Security.stripInaccessible(
                    AccessType.UPDATABLE,
                    new List<SObject>{ recordToUpdate },
                    true
                );
                List<SObject> lstToUpdate = decision.getRecords();
                try {
                    update lstToUpdate;
                    sucessIds.add(lstToUpdate[0].Id);
                } catch (exception e) {
                    throw new ReservationManagerException(e.getMessage());
                }
            }
        }
        return sucessIds;
    }

    public class Requests {
        @InvocableVariable
        public Id recordId;
    }

    public class ReservationManagerException extends Exception {
    }
}