es-base-code/main/default/objects/Customer_Fields__mdt/Customer_Fields__mdt.object-meta.xml
<CustomObject>
    <description>Used to determine appropriate fields for customer contact forms. Used to allow Lightning components to use Lead and Contact objects interchangeably.</description>
    <label>Customer Fields</label>
    <pluralLabel>Customer Fields</pluralLabel>
</CustomObject>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_City__c.field-meta.xml
<CustomField>
    <fullName>Customer_City__c</fullName>
    <inlineHelpText
    >Enter the API name of the field that holds the customer&apos;s city information.</inlineHelpText>
    <label>Customer City</label>
    <metadataRelationshipControllingField
    >Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields_Email</relationshipLabel>
    <relationshipName>Customer_Fields_Email</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields_Name</relationshipLabel>
    <relationshipName>Customer_Fields_Name</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_State__c.field-meta.xml
<CustomField>
    <fullName>Customer_State__c</fullName>
    <inlineHelpText>Enter the API name of the field that holds the customer&apos;s state information.</inlineHelpText>
    <label>Customer State</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Customer_Fields1</relationshipLabel>
    <relationshipName>Customer_Fields1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <metadataRelationshipControllingField>Customer_Fields__mdt.Sobject_Type__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

es-base-code/main/default/objects/Customer_Fields__mdt/fields/Sobject_Type__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type__c</fullName>
    <label>Sobject Type</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customer_Fields</relationshipLabel>
    <relationshipName>Customer_Fields</relationshipName>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

es-base-code/main/default/classes/CustomerServices.cls
public inherited sharing class CustomerServices {
    @auraEnabled(cacheable=true)
    public static Customer getCustomerFields(String objectType) {
        Customer customer;
        for (Customer_Fields__mdt c : [
            SELECT
                Customer_Name__r.QualifiedAPIName,
                Customer_Email__r.QualifiedAPIName,
                Customer_City__r.QualifiedAPIName,
                Customer_State__r.QualifiedAPIName,
                Customer_Status__r.QualifiedAPIName
            FROM Customer_Fields__mdt
            WHERE Sobject_Type__r.QualifiedAPIName = :objectType
            WITH SECURITY_ENFORCED
        ]) {
            customer = new Customer(
                c.Customer_Name__r.QualifiedAPIName,
                c.Customer_Email__r.QualifiedAPIName,
                c.Customer_City__r.QualifiedAPIName,
                c.Customer_State__r.QualifiedAPIName,
                '',
                ''
            );
        }
        return customer;
    }

    public class Customer {
        //attributes that we associate with customers
        @auraEnabled
        public String email { get; set; }

        @auraEnabled
        public String name { get; set; }

        @auraEnabled
        public String city { get; set; }

        @auraEnabled
        public String state { get; set; }

        @auraEnabled
        public String status { get; set; }

        @auraEnabled
        public String Id { get; set; }

        //putting them together, we get our wrapper object:
        public Customer(
            String name,
            String email,
            String city,
            String state,
            String status,
            String custId
        ) {
            this.name = name;
            if (String.isNotEmpty(email))
                this.email = email;
            if (String.isNotEmpty(city))
                this.city = city;
            if (String.isNotEmpty(state))
                this.state = state;
            if (String.isNotEmpty(status))
                this.status = status;
            if (String.isNotEmpty(custId))
                this.Id = custId;
        }
    }
}